name: python

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: [3.8, 3.9, '3.10', 3.11, 3.12]
        java: [8, 11, 17]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
        cache: 'pip'
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: ${{ matrix.java }}
    - run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-forked
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - run: |
        python -m pytest --forked
